import java.util.*;

public class Generated_636767781a6d9265ec018250 {
    /**Return a decision based on the message generated by the event and whether the given string is matched.**/
    public int decide(LoggingEvent event) {
        if (event.getMessage() == null)
            return 0;
        String msg = event.getMessage().toString();
        if (msg != null && msg.length() > 0) {
            for (String pattern : patterns) {
                Matcher matcher = Pattern.compile(pattern).matcher(msg);
                if (matcher.find()) {
                    return 1;
                }
            }
        }
        return 0;
    }
}