import java.util.*;

public class Generated_636767781a6d9265ec018250 {
    /**
     * Return a decision based on the message generated by the event and whether the given string is matched.
     */
    public int decide(LoggingEvent event) {
        if (event.getMessage() == null)
            return DENY;
        String msg = event.getMessage().toString();
        if (msg.indexOf(matchString) != -1)
            return ALLOW;
        else
            return DENY;
    }
}