import java.util.*;

public class Generated_636767781a6d9265ec018250 {
    /**Return a decision based on the message generated by the event and whether the given string is matched.*/
    public int decide(LoggingEvent event){
        if (event.getMessage().equals(message)) {
            return match;
        } else {
            return noMatch;
        }
    }
}